version: "3"

services:
  workspace:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        - workspace=/work
    command: sleep infinity
    volumes:
      - ..:/work:cached